# Generated by Django 3.0.7 on 2020-08-10 05:42

import LandingPage.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Cid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('days', models.CharField(blank=True, max_length=100, null=True)),
                ('months', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('audience', models.CharField(blank=True, choices=[('Students', 'Students'), ('Jobseekers', 'Jobseekers'), ('Freshers', 'Freshers'), ('Working Proffessionals', 'Working Proffessionals'), ('Freelencers', 'Freelencers'), ('Enterpreners', 'Enterpreners'), ('Others', 'Others')], max_length=100, null=True)),
                ('takeaway', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Courses',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('Vid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('session_date', models.DateField(blank=True, null=True)),
                ('session_start', models.TimeField(auto_now_add=True)),
                ('session_end', models.TimeField(auto_now_add=True)),
                ('days', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=LandingPage.models.content_file_name)),
            ],
            options={
                'verbose_name': 'Live Sessions',
                'verbose_name_plural': 'Live Sessions',
            },
        ),
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Details about Courses and Facilitator',
                'verbose_name_plural': 'Details about Courses and Facilitators',
            },
        ),
        migrations.CreateModel(
            name='OnlineCounsellingDetails',
            fields=[
                ('councelling_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='enter valid phone number', regex='^[6-9]\\d{9}$')])),
            ],
            options={
                'verbose_name': 'Free Councelling detail',
                'verbose_name_plural': 'Free Councelling details',
            },
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=500)),
                ('reply', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Support For Facilitators',
                'verbose_name_plural': 'Support For Facilitators',
            },
        ),
        migrations.CreateModel(
            name='VideoRecorded',
            fields=[
                ('Vid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('session_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=LandingPage.models.content_Rfile_name)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Course')),
            ],
            options={
                'verbose_name': 'Recorded Sessions',
                'verbose_name_plural': 'Recorded Sessions',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Category')),
            ],
            options={
                'verbose_name': 'Subcategories of Categories',
                'verbose_name_plural': 'Subcategories of Categories',
            },
        ),
    ]
