# Generated by Django 3.0.7 on 2020-08-10 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LandingPage', '0001_initial'),
        ('facilitators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='Fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator'),
        ),
        migrations.AddField(
            model_name='offer',
            name='Cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Course'),
        ),
        migrations.AddField(
            model_name='offer',
            name='Fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='subCat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.SubCategory'),
        ),
    ]
