# Generated by Django 3.0.7 on 2020-07-21 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0002_auto_20200714_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineCounsellingDetails',
            fields=[
                ('councelling_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='enter valid phone number', regex='^[6-9]\\d{9}$')])),
            ],
        ),
    ]
