# Generated by Django 3.0.7 on 2020-09-05 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
        ('LandingPage', '0002_auto_20200905_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='lerner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learners.Learners'),
        ),
    ]
