# Generated by Django 3.0.7 on 2020-08-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0007_auto_20200804_1351'),
        ('LandingPage', '0003_onlinecounsellingdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Courses', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Details about Courses and Facilitator', 'verbose_name_plural': 'Details about Courses and Facilitators'},
        ),
        migrations.AlterModelOptions(
            name='onlinecounsellingdetails',
            options={'verbose_name': 'Free Councelling detail', 'verbose_name_plural': 'Free Councelling details'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategories of Categories', 'verbose_name_plural': 'Subcategories of Categories'},
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator'),
        ),
    ]
