# Generated by Django 3.0.7 on 2020-09-05 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
        ('LandingPage', '0003_auto_20200905_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='lerner',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='learners.Learners'),
            preserve_default=False,
        ),
    ]
