# Generated by Django 3.0.9 on 2020-08-14 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0003_auto_20200811_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={},
        ),
    ]
