# Generated by Django 3.0.7 on 2020-08-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0005_otp'),
        ('LandingPage', '0004_auto_20200814_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='Cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='LandingPage.Course'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitators', to='facilitators.Facilitator'),
        ),
    ]
