# Generated by Django 3.0.7 on 2020-08-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0007_auto_20200804_1351'),
        ('LandingPage', '0004_auto_20200804_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=500)),
                ('reply', models.TextField(blank=True, max_length=500, null=True)),
                ('Fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator')),
            ],
            options={
                'verbose_name': 'Queries Of Facilitators',
                'verbose_name_plural': 'Queries of Facilitators',
            },
        ),
    ]
