# Generated by Django 3.0.7 on 2020-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0004_auto_20200806_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Audience',
            field=models.CharField(blank=True, choices=[('Students', 'Students'), ('Jobseekers', 'Jobseekers'), ('Freshers', 'Freshers'), ('Working Proffessionals', 'Working Proffessionals'), ('Jobseekers', 'Jobseekers'), ('Freelencers', 'Freelencers'), ('Enterpreners', 'Enterpreners'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='takeaway',
            field=models.TextField(blank=True, null=True),
        ),
    ]
