# Generated by Django 3.0.7 on 2020-09-05 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
        ('LandingPage', '0005_auto_20200905_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='lerner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learners.Learners'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='rating',
            index_together=set(),
        ),
    ]
