# Generated by Django 3.0.7 on 2020-08-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0005_auto_20200806_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Audience',
            new_name='audience',
        ),
    ]
