# Generated by Django 3.0.7 on 2020-08-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0005_otp'),
        ('LandingPage', '0005_auto_20200816_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='offering',
            field=models.ManyToManyField(through='LandingPage.offer', to='facilitators.Facilitator'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Course'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='Fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator'),
        ),
    ]
