# Generated by Django 3.0.7 on 2020-09-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0006_auto_20200905_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
