# Generated by Django 3.0.7 on 2020-08-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0006_auto_20200806_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
