# Generated by Django 3.0.7 on 2020-08-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0007_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='audience',
            field=models.CharField(blank=True, choices=[('Students', 'Students'), ('Jobseekers', 'Jobseekers'), ('Freshers', 'Freshers'), ('Working Proffessionals', 'Working Proffessionals'), ('Freelencers', 'Freelencers'), ('Enterpreners', 'Enterpreners'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
