# Generated by Django 3.0.7 on 2020-08-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0007_auto_20200818_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('categories', models.CharField(choices=[('Categories', 'Categories..'), ('Learners', 'Learners'), ('Facilitators', 'Facilitators'), ('Corporates', 'Corporates'), ('Campus', 'Campus'), ('Others', 'Others')], max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='CorporatesTalks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('training_need', models.CharField(choices=[('Select', 'Select..'), ('Digital Training', 'Digital Training'), ('Business Training', 'Business Training'), ('IT Training', 'IT Training'), ('Marketing Training', 'Marketing Training'), ('Others', 'Others')], max_length=100)),
                ('message', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('check', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Corporate Talks',
                'verbose_name_plural': 'Corporate Talks',
            },
        ),
    ]
