# Generated by Django 3.0.7 on 2020-08-21 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0008_contactus_corporatestalks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_video', to='LandingPage.Course'),
        ),
    ]
