# Generated by Django 3.0.7 on 2020-09-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0010_auto_20200821_0227'),
        ('LandingPage', '0008_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='Fid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator'),
        ),
    ]
