# Generated by Django 3.0.7 on 2020-08-07 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0008_auto_20200806_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='code',
        ),
    ]
