# Generated by Django 3.0.7 on 2020-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0009_auto_20200807_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='session_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='session_duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
