# Generated by Django 3.0.7 on 2020-08-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0011_otp_txt'),
        ('LandingPage', '0009_auto_20200821_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='offering',
            field=models.ManyToManyField(related_name='offering', through='LandingPage.offer', to='facilitators.Facilitator'),
        ),
    ]
