# Generated by Django 3.0.7 on 2020-09-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0010_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
