# Generated by Django 3.0.7 on 2020-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0012_auto_20200918_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default/course_thumbnail.png', null=True, upload_to='courses/'),
        ),
    ]
