# Generated by Django 3.0.7 on 2020-09-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0012_auto_20200922_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
