# Generated by Django 3.0.7 on 2020-09-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0013_auto_20200926_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.IntegerField(blank=True, max_length=59, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='months',
            field=models.IntegerField(blank=True, max_length=12, null=True),
        ),
    ]
