# Generated by Django 3.0.7 on 2020-09-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0013_auto_20200918_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=100),
        ),
    ]
