# Generated by Django 3.0.7 on 2020-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0014_auto_20200926_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
