# Generated by Django 3.0.7 on 2020-10-08 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0016_auto_20200926_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Category'),
            preserve_default=False,
        ),
    ]
