# Generated by Django 3.0.8 on 2020-10-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0017_course_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='categories',
            new_name='categorie',
        ),
    ]
