# Generated by Django 3.0.7 on 2020-08-04 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilitators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experience',
            name='facilitator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilitators.Applicants'),
        ),
        migrations.AddField(
            model_name='facilitator',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facilitatorqueries',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilitators.Applicants'),
        ),
    ]
