# Generated by Django 3.0.9 on 2020-08-24 20:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
        ('facilitators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilitators.Facilitator')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.Learners')),
            ],
            options={
                'unique_together': {('learner', 'facilitator')},
                'index_together': {('learner', 'facilitator')},
            },
        ),
    ]
