# Generated by Django 3.0.7 on 2020-08-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0002_auto_20200804_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='email',
        ),
    ]
