# Generated by Django 3.0.7 on 2020-08-13 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0003_auto_20200811_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='facilitator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='facilitators.Applicants'),
        ),
        migrations.AlterField(
            model_name='facilitator',
            name='profile',
            field=models.ImageField(blank=True, default='default/profile.png', null=True, upload_to='Mentor_profiles/'),
        ),
    ]
