# Generated by Django 3.0.7 on 2020-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='Linkedin_Url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Website_Url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='Youtube_Url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
