# Generated by Django 3.0.7 on 2020-08-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0003_remove_applicants_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='facilitators.Applicants'),
        ),
    ]
