# Generated by Django 3.0.7 on 2020-08-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0004_auto_20200804_2240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicants',
            options={'verbose_name': 'Registered Applicant', 'verbose_name_plural': 'Registered Applicants'},
        ),
    ]
