<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-08-14 08:44
=======
# Generated by Django 3.0.9 on 2020-08-14 13:17
>>>>>>> 651ce72b0bf6175ed2b6a803f10da3d334f1d3dd

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0004_auto_20200813_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
            ],
        ),
    ]
