# Generated by Django 3.0.7 on 2020-08-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0005_auto_20200804_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='zipcode',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
