# Generated by Django 3.0.7 on 2020-08-17 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0005_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitatorqueries',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='facilitators.Applicants'),
        ),
    ]
