# Generated by Django 3.0.7 on 2020-08-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0006_auto_20200817_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'Reset OTP', 'verbose_name_plural': 'Reset OTPS'},
        ),
    ]
