# Generated by Django 3.0.7 on 2020-08-20 17:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0007_auto_20200819_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='Bio',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
