# Generated by Django 3.0.7 on 2020-08-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilitators', '0009_auto_20200820_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitator',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
