# Generated by Django 3.0.7 on 2020-08-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0009_auto_20200821_1338'),
        ('facilitators', '0010_auto_20200821_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='txt',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Course'),
            preserve_default=False,
        ),
    ]
