# Generated by Django 3.0.7 on 2020-08-10 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LandingPage', '0002_auto_20200810_1112'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('Lid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=13)),
                ('PAddress', models.TextField(blank=True, null=True)),
                ('TAddress', models.TextField(blank=True, null=True)),
                ('profile', models.ImageField(blank=True, default='default.png', null=True, upload_to='learners_profiles/')),
                ('Bio', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(blank=True, default='Active', max_length=100, null=True)),
                ('enrolled', models.ManyToManyField(related_name='enroll', to='LandingPage.Course')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Learner',
                'verbose_name_plural': 'Learners',
            },
        ),
    ]
