# Generated by Django 3.0.7 on 2020-09-17 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('certificate_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('learner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learner_certificate', to='learners.Learners')),
            ],
        ),
    ]
