# Generated by Django 3.0.7 on 2020-08-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learners',
            name='added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='learners',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
