# Generated by Django 3.0.7 on 2020-09-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
