# Generated by Django 3.0.7 on 2020-08-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_auto_20200811_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='LQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(max_length=500)),
                ('reply', models.TextField(blank=True, max_length=500, null=True)),
                ('added', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.Learners')),
            ],
            options={
                'verbose_name': 'Support For Learners',
                'verbose_name_plural': 'Support For Learners',
            },
        ),
    ]
