# Generated by Django 3.0.7 on 2020-08-25 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0003_lqueries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
