# Generated by Django 3.0.7 on 2020-09-03 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0012_course_language'),
        ('learners', '0003_lqueries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Course')),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.Learners')),
            ],
            options={
                'verbose_name': 'Course Reviews',
                'verbose_name_plural': 'Course Reviews',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', models.CharField(max_length=2000)),
                ('Rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.Reviews')),
            ],
        ),
    ]
