# Generated by Django 3.0.7 on 2020-08-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0010_auto_20200828_1337'),
        ('learners', '0003_lqueries'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Course')),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.Learners')),
            ],
            options={
                'verbose_name': 'Courses of Learners',
                'verbose_name_plural': 'Courses of Learners',
            },
        ),
    ]
