# Generated by Django 3.0.7 on 2020-09-17 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0010_course_level'),
        ('learners', '0003_certificate_certificate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_certificate', to='LandingPage.Course'),
        ),
    ]
