# Generated by Django 3.0.7 on 2020-08-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LandingPage', '0010_auto_20200828_1337'),
        ('learners', '0004_learnercourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=1000)),
                ('Cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LandingPage.Course')),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.Learners')),
            ],
            options={
                'verbose_name': 'Course Reviews',
                'verbose_name_plural': 'Course Reviews',
            },
        ),
        migrations.DeleteModel(
            name='LearnerCourse',
        ),
    ]
