# Generated by Django 3.0.7 on 2020-09-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0005_remove_learners_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='learners_profiles'),
        ),
    ]
