# Generated by Django 3.0.7 on 2020-09-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0005_auto_20200926_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='added',
            new_name='addedenroll',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='updated',
            new_name='updatedenroll',
        ),
    ]
