# Generated by Django 3.0.7 on 2020-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0006_auto_20200928_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learners',
            name='profile',
            field=models.ImageField(blank=True, default='default/profile.png', null=True, upload_to='learners_profiles'),
        ),
    ]
