# Generated by Django 3.0.7 on 2020-10-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0006_auto_20200926_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learners',
            name='Bio',
        ),
        migrations.AlterField(
            model_name='learners',
            name='profile',
            field=models.ImageField(blank=True, default='default/profile.png', null=True, upload_to='learners_profiles'),
        ),
    ]
