# Generated by Django 3.0.7 on 2020-09-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0006_reviews_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reply',
            field=models.CharField(default='No replies yet', max_length=1000),
        ),
    ]
