# Generated by Django 3.0.7 on 2020-09-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0007_reviews_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='reply',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', models.CharField(max_length=2000)),
                ('Rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learners.Reviews')),
            ],
        ),
    ]
