# Generated by Django 3.0.7 on 2020-08-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Visiter'), (1, 'Learner'), (2, 'Facilitator'), (3, 'Admin')], null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
