# Generated by Django 3.0.7 on 2020-07-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_auto_20200723_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Visiter'), (1, 'Learner'), (2, 'Facilitator'), (3, 'Admin')], null=True),
        ),
    ]
